FROM python:3.9-slim-buster

WORKDIR /app

COPY producer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY producer/ecommerce_producer_fast.py .
COPY utils.py .
COPY confluent_cluster_api.txt .
COPY ecommerce-events-history-in-electronics-store ecommerce-events-history-in-electronics-store

CMD ["python", "ecommerce_producer_fast.py"]